stages:
  - deploy_to_sonatype

variables:
  REGISTRY: 486234852809.dkr.ecr.us-east-1.amazonaws.com

# From the tagged repo, push the release artifact
deploy_to_sonatype:
  stage: deploy_to_sonatype

  rules:
    # All releases are manual
    - when: manual
      allow_failure: true

  tags:
    - "runner:docker"

  image: registry.ddbuild.io/docker:20.10.13-gbi-focal

  script:
    # Ensure we don't print commands being run to the logs during credential
    # operations
    - set +x
    - echo $DOCKER_HOST
    - sleep 10000
