stages:
  - deploy_to_sonatype

variables:
  REGISTRY: 486234852809.dkr.ecr.us-east-1.amazonaws.com

# From the tagged repo, push the release artifact
deploy_to_sonatype:
  stage: deploy_to_sonatype

  rules:
    # All releases are manual
    - when: manual
      allow_failure: true

  tags:
    - "runner:docker"

  image: registry.ddbuild.io/docker:20.10.13-gbi-focal

  script:
    # Ensure we don't print commands being run to the logs during credential
    # operations
    - set +x
    - echo "Creating container http server"
    - container_id=$(docker run -P -d strm/helloworld-http@sha256:bd44b0ca80c26b5eba984bf498a9c3bab0eb1c59d30d8df3cb2c073937ee4e45)
    - echo "Call the http server from this container"
    - container_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $container_id)
    # Works when addressing the container IP directly
    - curl http://$container_ip
    # When using the automatically assigned port, it fails to connect
    - host_mapped_url=$(docker inspect -f '{{range .NetworkSettings.Ports}}{{range .}}{{println .HostIp .HostPort}}{{end}}{{end}}' $container_id | tr ' ' ':' | head -n 1)
    - curl http://$host_mapped_url
