domains:
    test_1:
        bean_count: 5
        attribute_count: 2
        tabular_count: 3
        composite_count: 4
    test_2:
        bean_count: 1
        attribute_count: 1
        tabular_count: 1
        composite_count: 1


