version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  commit-message:
    prefix: 'chore(ci): '
  groups:
    gh-actions-packages:
      patterns:
      - '*'
  cooldown:
    default-days: 14
